const GET_ALL_USERS = 'GET_ALL_USERS';
const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
const LOADING_USER_ON = 'LOADING_USER_ON';
const LOADING_USER_OFF = 'LOADING_USER_OFF';
const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
const AUTH_USER = 'AUTH_USER';
const SET_SELECTED_USER = 'SET_SELECTED_USER';
const SET_EQUIPEMENT_LOADING_ON = 'SET_EQUIPEMENT_LOADING_ON';
const SET_EQUIPEMENT_LOADING_OFF = 'SET_EQUIPEMENT_LOADING_OFF';
const GET_EQUIPEMENT_LIST = 'GET_EQUIPEMENT_LIST';
const SET_SELECTED_EQUIPMENT = 'SET_SELECTED_EQUIPMENT';
const SET_SELECTED_ERROR = 'SET_SELECTED_ERROR';
const GET_ALL_ERRORS = 'GET_ALL_ERRORS';
const SET_SELECTED_ERROR_ID = 'SET_SELECTED_ERROR_ID';
const SET_SELECTED_ERROR_ITEM = 'SET_SELECTED_ERROR_ITEM';
export {
  GET_ALL_USERS,
  GET_ALL_USERS_SUCCESS,
  LOADING_USER_OFF,
  LOADING_USER_ON,
  AUTH_USER_SUCCESS,
  AUTH_USER,
  SET_SELECTED_USER,
  SET_EQUIPEMENT_LOADING_OFF,
  SET_EQUIPEMENT_LOADING_ON,
  GET_EQUIPEMENT_LIST,
  SET_SELECTED_EQUIPMENT,
  GET_ALL_ERRORS,
  SET_SELECTED_ERROR,
  SET_SELECTED_ERROR_ID,
  SET_SELECTED_ERROR_ITEM,
};
